### ISSUE TITLE
Licencia

### ISSUE THREAD

**Issue by JonAnderDiez** [JonAnderDiez/ExpediaScraper#2]
Seleccionar una licencia para el dataset y explicar el motivo de su selección:

- Released Under CC0: Public Domain License
- Released Under CC BY-NC-SA 4.0 License
- Released Under CC BY-SA 4.0 License
- Database released under Open Database License, individual contents under Database Contents License
- Other (specified above)
- Unknown License

**Comment by benataranburu** [comment]
Propongo "open database license"
