### ISSUE TITLE
Generalizar para una lista de aeropuertos de salida y ciudades de llegada

### ISSUE THREAD

**Issue by JonAnderDiez** [JonAnderDiez/ExpediaScraper#8]
Generalizar una vez que funcione bien el trayecto Bilbao-Londres con la lista de ciudades de salida y las de llegada que están especificadas en el documento Word.

**Comment by benataranburu** [comment]
Estoy desarrollando esta funcionalidad

**Comment by benataranburu** [comment]
Issue resuelto
